version: '3.7'
services:
  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    image: flask
    restart: unless-stopped
    ports:
      - 5001:5000
    environment:
      FLASK_ENV: production
      APP_ENV: 'prod'
      APP_PORT: 5000
      MONGODB_DATABASE: tradeLogs
      MONGODB_USERNAME: tradeLogsUser
      MONGODB_PASSWORD: kill2mkt
      MONGODB_HOSTNAME: 192.168.1.71
    volumes:
      - ./app:/var/www/
      -  /home/adrien/tradeLogs:/tradeLogs
    networks:
      - frontend
      - backend

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: webserver
    container_name: webserver
    restart: unless-stopped
    environment:
      FLASK_ENV: production
      APP_ENV: 'prod'
      APP_NAME: 'webserver'
      APP_DEBUG: 'true'
      SERVICE_NAME: 'webserver'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - flask
    networks:
      - frontend

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=production
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - flask

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  nginxdata:
    driver: local